switch:
  - platform: megad
    ip: 192.168.88.14
    pass: sec
    name: Desktop test
    ports:
      0:
        name: Кухня стіл
      5:
        name: Кухня освітлення
      6:
        name: Коридор освітлення


light:
  - platform: megad
    ip: 192.168.88.14
    pass: sec
    name: Desktop test
    ports:
      7:
        name: Кухня освітлення
      8:
        name: Кухня стіл

