megad:
  - name: Desktop test
    id: kitchen
    ip: 192.168.88.14
    password: sec
    controller: 2561



switch:
  - platform: megad
    devices:
      kitchen:
        0:
          name: Кухня стіл
        5:
          name: Кухня освітлення
        6:
          name: Коридор освітлення


light:
  - platform: megad
    devices:
      kitchen:
        7:
          name: Кухня освітлення
        8:
          name: Кухня стіл

